# Generated by Django 3.0.8 on 2020-07-22 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200721_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ExternAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_account', models.CharField(max_length=20)),
                ('nombre_cuenta', models.CharField(blank=True, max_length=200, null=True)),
                ('limite_diario', models.IntegerField(blank=True, default=1000, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extern_account_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
