# Generated by Django 3.0.8 on 2020-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200722_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_account',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
